name: Build and Publish Wheels

on:
  push:
    tags:
      - "v*.*.*" # e.g., v1.0.0
  workflow_dispatch: # manual trigger

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Only for installing cibuildwheel

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist

      - name: Check built wheels
        run: ls dist

      - name: Verify wheels
        run: python -m twine check dist/*
